#!/usr/bin/env bash
# This bash script fixes the issues with nginx server problems from listening on port 80.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart