#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=0
y=1
while [ $x -le 12 ]
do
  echo "Hour: $x"
  while [ $y -le 59 ]
  do
  	echo $y
  	y=$(( y + 1 ))
  done	
  y=1
  x=$(( x + 1 ))
done
